#!/bin/bash

db_name=$1
db_host=$2

my_root_user=$(crudini --get /etc/elsacp/elsacp.conf 'config' 'my_root_user')
my_root_pass=$(crudini --get /etc/elsacp/elsacp.conf 'config' 'my_root_pass')
mysql_server=$(crudini --get /etc/elsacp/elsacp.conf 'config' 'mysql_server')

#
# Check if running by root
#
if [[ $EUID -ne 0 ]]; then
   echo -e '\nThis script must be run as root.\n'
   exit 1
fi

if [ -z "$1" ] || [ -z "$2" ] ; then
   echo -e '\nPlease complete the parameters.'
   echo -e '\nExample: elsa-mysql-drop awesomedb dbhost\n'
   exit 1 
fi

prompt_confirm() {
  echo -e '\n'
  while true; do
    read -r -n 1 -p "${1:-Continue?} [y/n]: " REPLY
    case $REPLY in
      [yY]) echo ; return 0 ;;
      [nN]) echo ; return 1 ;;
      *) printf " \033[31m %s \n\033[0m" "invalid input"
    esac 
  done  
  echo -e '\n'
}

prompt_confirm "This action will drop the database and user. Are you sure?" || exit 0

mysql -h $mysql_server -uroot -p$my_root_pass -e "DROP DATABASE IF EXISTS $db_name"
mysql -h $mysql_server -uroot -p$my_root_pass -e "DROP USER '$db_name'@'$db_host';"
mysql -h $mysql_server -uroot -p$my_root_pass -e "FLUSH PRIVILEGES"

if [ $(cat /etc/elsacp/mysqluser.txt | grep -c $db_name) -eq 1 ]; then
  sed -i '/'$db_name'/d' /etc/elsacp/mysqluser.txt
fi

echo -e "\nDatabase $db_name and user $db_name at $db_host deleted!\n"
