#!/bin/bash

#
# Check if running by root
#
if [[ $EUID -ne 0 ]]; then
   echo -e '\nThis script must be run as root.\n'
   exit 1
fi

echo 'Stoping MariaDB...'
systemctl stop mysql

echo 'Stoping php-fpm...'
systemctl stop php5.6-fpm
systemctl stop php7.2-fpm

echo 'Stoping nginx...'
systemctl stop nginx

echo -e '\nDaemons stoped\n'
