#!/bin/bash

DOMAIN=$1
SERVIP=$(curl -s v4.ifconfig.co)
CHCKIP=$(dig $DOMAIN +short)
BASENM=$(echo $DOMAIN | cut -d"." -f1)

#
# Check if running by root
#
if [[ $EUID -ne 0 ]]; then
   echo -e '\nThis script must be run as root.\n'
   exit 1
fi

if [ -z "$1" ]; then
   echo -e '\nPlease input the domain name. Example:\n'
   echo -e '  elsa-vhost-enable domain.com.conf-disable'
   echo -e '  elsa-vhost-enable domain.com-ssl.conf-disable\n'
   exit 1
fi

if [[ ! -f "/etc/nginx/vhost.d/$DOMAIN-disable" ]]; then
    echo -e "\nVirtualHost $DOMAIN dosen't exists or already enabled!\n"
    exit 1
fi

echo -e '\nEnabling virtualhost...'
mv /etc/nginx/vhost.d/$DOMAIN-disable /etc/nginx/vhost.d/$DOMAIN

echo -e 'Restarting web server...'
systemctl restart nginx

echo -e "\nVirtual host for domain $DOMAIN was disabled!\n"
