#!/bin/bash

SUBCMD=$1

#
# Check if running by root
if [[ $EUID -ne 0 ]]; then
   echo -e '\nThis script must be run as root.\n'
   exit 1
fi

if [ -z "$1" ]; then
   echo -e "\nPlease include the command: $0 start|stop|restart\n"
   exit 1
fi
echo -e '\n'

echo $SUBCMD"ing MariaDB..."
systemctl $SUBCMD mysql

echo $SUBCMD"ing php-fpm..."
systemctl $SUBCMD php5.6-fpm
systemctl $SUBCMD php7.2-fpm

echo $SUBCMD"ing nginx..."
systemctl $SUBCMD nginx

echo $SUBCMD"ing pure-fptd..."
systemctl $SUBCMD pure-ftpd

echo -e '\nDaemons restarted\n'
