#!/bin/bash

#
# Check if running by root
#
if [[ $EUID -ne 0 ]]; then
   echo -e '\nThis script must be run as root.\n'
   exit 1
fi

echo 'Starting MariaDB...'
systemctl start mysql

echo 'Starting php-fpm...'
systemctl start php5.6-fpm
systemctl start php7.2-fpm

echo 'Starting nginx...'
systemctl start nginx

echo -e '\nDaemons started\n'
