#!/bin/bash

DOMAIN=$1
BASENM=$(echo $DOMAIN | cut -d"." -f1)
SERVIP=$(curl -s v4.ifconfig.co)
CHCKIP=$(ping -q -c1 -t1 $DOMAIN | grep PING | sed -e "s/).*//" | sed -e "s/.*(//")
EMAIL=$(crudini --get /etc/elsacp/elsacp.conf 'config' 'certbot_email')

#
# Check if running by root
if [[ $EUID -ne 0 ]]; then
   echo -e '\nThis script must be run as root.\n'
   exit 1
fi

if [ -z "$1" ]; then
   echo -e '\nPlease input the domain name. Example: elsa-ssl-renew domain.com\n'
   exit 1
fi

if [ ! -d "/etc/letsencrypt/live/$DOMAIN" ]; then
    echo -e "\nSSL Certificate doesn't exist for domain $DOMAIN, please use create command!\n"
    exit 1
fi

if [ "$CHCKIP" != "$SERVIP" ];then
    echo -e "\nDomain $DOMAIN not pointed to this server."
    echo -e "\nThe domain still pointed to $CHCKIP"
    echo -e "\nPlease fix this problem dude!\n"
    exit 1
else
    echo -e '\nStopping web server service...'
    systemctl stop nginx

    echo -e 'Renewing Letsencrypt SSL Certificate...\n'
    #certbot renew --pre-hook "systemctl stop nginx" --post-hook "systemctl start nginx"
    certbot certonly -n --standalone --quiet --agree-tos --register-unsafely-without-email -d $DOMAIN

    echo -e '\nStarting web server service...'
    systemctl restart nginx

    echo -e '\nAll done, thank you!\n'
fi
