#!/bin/bash

ftp_user=$1
ftp_pass=$2
ftp_home=$3

# Running by root?
if [[ $EUID -ne 0 ]]; then
   echo -e '\nThis script must be run as root.\n'
   exit 1
fi

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] ; then
   echo -e '\nPlease complete the parameters.'
   echo -e '\nExample: elsa-ftp-add ftp_user ftp_pass /path/to/home/directory\n'
   exit 1 
fi

if [ $(cat /etc/pure-ftpd/pureftpd.passwd | grep -c "$ftpuser") ! -eq 0 ]; then
    echo "That user doesn't exists bro!"
    exit 1
fi

pure-pw userdel $ftp_user -m ; pure-pw mkdb

echo -e "\nFTP user $ftp_user deleted, but home directory not removed!\n"
