#!/bin/bash

DOMAIN=$1
SERVIP=$(curl -s v4.ifconfig.co)
CHCKIP=$(dig $DOMAIN +short)
BASENM=$(echo $DOMAIN | cut -d"." -f1)
certbot_email=$(crudini --get /etc/elsacp.cnf 'config' 'certbot_email')

#
# Check if running by root
#
if [[ $EUID -ne 0 ]]; then
   echo -e '\nThis script must be run as root.\n'
   exit 1
fi

if [ -z "$1" ]; then
   echo -e '\nPlease input the domain name. Example: elsa-ssl-create domain.com\n'
   exit 1
fi

if [ -d "/etc/letsencrypt/live/$DOMAIN" ]; then
    echo -e "\nSSL Certificate already exist for domain $DOMAIN, please use renew command!\n"
    exit 1
fi

if [ "$CHCKIP" != "$SERVIP" ];then
    echo -e "\nDomain $DOMAIN not pointed to this server."
    echo -e "\nThe domain still pointed to $CHCKIP"
    echo -e "\nPlease fix this problem dude!\n"
    exit 1
else
    echo -e '\nStopping web server service...'
    systemctl stop nginx

    echo -e 'Generating Letsencrypt SSL Certificate...\n'
    certbot certonly --standalone --agree-tos -m $certbot_email -d $DOMAIN

    echo -e '\nStarting web server service...'
    systemctl restart nginx

    echo -e '\nAll done, thank you!\n'
fi
