#!/bin/bash

ftp_user=$1

# Running by root?
if [[ $EUID -ne 0 ]]; then
   echo -e '\nThis script must be run as root.\n'
   exit 1
fi

if [ -z "$1" ] ; then
   echo -e '\nPlease complete the parameters.'
   echo -e '\nExample: elsa-ftp-del ftp_user\n'
   exit 1 
fi

if [ $(cat /etc/pure-ftpd/pureftpd.passwd | grep -c "$ftpuser") ! -eq 0 ]; then
    echo "That user doesn't exists bro!"
    exit 1
fi

pure-pw userdel $ftp_user -m ; pure-pw mkdb

if [ $(cat /etc/elsacp-ftpuser.txt | grep -c $ftp_user) -eq 1 ]; then sed -i '/'$ftp_user'/d' /etc/elsacp-ftpuser.txt ; fi

echo -e "\nFTP user $ftp_user deleted, but home directory not removed!\n"
