#!/bin/bash

# Check if running by root
if [[ $EUID -ne 0 ]]; then
   echo -e -e '\nThis script must be run as root.\n'
   exit 1
fi

echo -e "\n\e[0;35mUpdating packages list\e[0m"
apt update

echo -e "\n\e[0;35mUpdating system\e[0m"
apt full-upgrade -y

echo -e "\n\e[0;35mRemoving uneeded packages\e[0m"
apt autoremove -y

echo -e "\n\e[0;35mCleaning packages\e[0m"
apt clean

echo -e "\n\e[0;35mEverything is up to date boss\n\e[0m"
