#!/bin/bash

ftp_user=$1
ftp_pass=$2
ftp_home=$3

# Running by root?
if [[ $EUID -ne 0 ]]; then
   echo -e '\nThis script must be run as root.\n'
   exit 1
fi

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] ; then
   echo -e '\nPlease complete the parameters.'
   echo -e '\nExample: elsa-ftp-add ftp_user ftp_pass /path/to/home/directory\n'
   exit 1 
fi

if [ $(cat /etc/pure-ftpd/pureftpd.passwd | grep -c "$ftpuser") ! -eq 0 ]; then
    echo "That user already exists bro!"
    exit 1
fi

echo -e "$ftp_pass\n$ftp_pass" | pure-pw useradd $ftp_user -u ftpuser -g www-data -d $ftp_home -m
mkdir -p $ftp_home ; chown -R ftpuser:www-data $ftp_home ; pure-pw mkdb

if [ $(cat /etc/elsacp-ftpuser.txt | grep -c $ftp_user) -eq 0 ]; then echo "$ftp_user:$ftp_pass" >> /etc/elsacp-ftpuser.txt ; fi

echo -e "\nFTP user $ftp_user created with password: $ftp_pass\n"
