#!/bin/bash

db_name=$1

my_root_user=$(crudini --get /etc/elsacp/elsacp.conf 'config' 'my_root_user')
my_root_pass=$(crudini --get /etc/elsacp/elsacp.conf 'config' 'my_root_pass')
mysql_server=$(crudini --get /etc/elsacp/elsacp.conf 'config' 'mysql_server')

#
# Check if running by root
if [[ $EUID -ne 0 ]]; then
   echo -e '\nThis script must be run as root.\n'
   exit 1
fi

if [ -z "$1" ] ; then
   echo -e '\nPlease complete the parameters.'
   echo -e '\nExample: elsa-mysql-backup awesomedb\n'
   exit 1 
fi

mysqldump -h $mysql_server -uroot -p$my_root_pass $db_name > $db_name-$(date +%Y%m%d).sql

echo -e "\nBackup for database $db_name was created!\n"
